global:
  environment: staging
  domain: staging.example.com

  mongodb:
    enabled: true
    auth:
      rootPassword: "staging-password"
      username: "money"
      password: "staging-password"
      database: "money_calculator_staging"

  redis:
    enabled: true
    auth:
      password: "staging-password"

aichat-bot:
  enabled: true
  replicaCount: 2
  
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 192Mi
  
  ingress:
    hosts:
      - host: chat.staging.example.com
        paths:
          - path: /
            pathType: Prefix

calculate-money:
  enabled: true
  replicaCount: 2
  
  resources:
    limits:
      cpu: 300m
      memory: 384Mi
    requests:
      cpu: 150m
      memory: 192Mi
  
  config:
    jwt:
      secretKey: "staging-secret-key"
  
  ingress:
    hosts:
      - host: api.money.staging.example.com
        paths:
          - path: /
            pathType: Prefix
  
  frontend:
    enabled: true
    replicaCount: 2
    config:
      apiBaseUrl: "https://api.money.staging.example.com/api/v1"
      env: "staging"
    
    ingress:
      hosts:
        - host: money.staging.example.com
          paths:
            - path: /
              pathType: Prefix

mongodb:
  persistence:
    size: 8Gi

redis:
  master:
    persistence:
      size: 2Gi

# Enable auto-scaling in staging
aichat-bot:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70

calculate-money:
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 4
    targetCPUUtilizationPercentage: 70
