apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calculate-money.fullname" . }}-config
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
data:
  config.yaml: |
    server:
      host: {{ .Values.config.server.host }}
      port: {{ .Values.config.server.port }}
      cors:
        allow_origins: {{ .Values.config.server.cors.allowOrigins | toJson }}
        allow_methods: {{ .Values.config.server.cors.allowMethods | toJson }}
        allow_headers: {{ .Values.config.server.cors.allowHeaders | toJson }}
    
    jwt:
      algorithm: {{ .Values.config.jwt.algorithm }}
      access_token_expire_minutes: {{ .Values.config.jwt.accessTokenExpireMinutes }}

---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "calculate-money.frontend.fullname" . }}-config
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
data:
  .env: |
    API_BASE_URL={{ .Values.frontend.config.apiBaseUrl }}
    NODE_ENV={{ .Values.frontend.config.env }}
{{- end }}
