apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculate-money.fullname" . }}
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "calculate-money.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "calculate-money.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "calculate-money.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: MONGODB_URI
              valueFrom:
                secretKeyRef:
                  name: {{ include "calculate-money.fullname" . }}-mongodb
                  key: mongodb-uri
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ include "calculate-money.fullname" . }}-jwt
                  key: secret-key
            - name: JWT_ALGORITHM
              value: {{ .Values.config.jwt.algorithm }}
            - name: ACCESS_TOKEN_EXPIRE_MINUTES
              value: {{ .Values.config.jwt.accessTokenExpireMinutes | quote }}
            - name: SERVER_HOST
              value: {{ .Values.config.server.host }}
            - name: SERVER_PORT
              value: {{ .Values.config.server.port | quote }}
            - name: CORS_ALLOW_ORIGINS
              value: {{ join "," .Values.config.server.cors.allowOrigins | quote }}
            - name: CORS_ALLOW_METHODS
              value: {{ join "," .Values.config.server.cors.allowMethods | quote }}
            - name: CORS_ALLOW_HEADERS
              value: {{ join "," .Values.config.server.cors.allowHeaders | quote }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}

---
{{- if .Values.frontend.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "calculate-money.frontend.fullname" . }}
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "calculate-money.frontend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "calculate-money.frontend.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            - name: API_BASE_URL
              value: {{ .Values.frontend.config.apiBaseUrl }}
            - name: NODE_ENV
              value: {{ .Values.frontend.config.env }}
          resources:
            {{- toYaml .Values.frontend.resources | nindent 12 }}
{{- end }}
