apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calculate-money.fullname" . }}-jwt
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ .Values.config.jwt.secretKey | b64enc }}

---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "calculate-money.fullname" . }}-mongodb
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.mongodb.enabled }}
  mongodb-uri: {{ printf "mongodb://%s:%s@%s-mongodb:27017/%s" .Values.mongodb.auth.username .Values.mongodb.auth.password (include "calculate-money.fullname" .) .Values.mongodb.auth.database | b64enc }}
  {{- else }}
  mongodb-uri: {{ .Values.mongodb.uri | b64enc }}
  {{- end }}
