apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculate-money.fullname" . }}
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calculate-money.selectorLabels" . | nindent 4 }}

---
{{- if .Values.frontend.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "calculate-money.frontend.fullname" . }}
  labels:
    {{- include "calculate-money.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: {{ .Values.frontend.service.type }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "calculate-money.frontend.selectorLabels" . | nindent 4 }}
{{- end }}
